apiVersion: v1
kind: ConfigMap
metadata:
  name: future-backend-config
  namespace: future-backend
data:
  NODE_ENV: "development"
  development.yml: |
    app:
      name: "future-backend"
      prefix: "v1"
      port: 3000
      jwt_access_token_secret: "dev-jwt-secret-key-change-in-production"
      jwt_access_token_expiration_time: "86400"
      jwt_refresh_token_expiration_time: "604800"
      signature_ignore: true

    jwt_key:
      public: ""
      private: ""

    secret:
      key: "dev-secret-key"

    _master:
      type: "mysql"
      host: "exchange-dev-mysql.clhjvle5bfjb.ap-northeast-2.rds.amazonaws.com"
      port: 3306
      username: "admin"
      password: "zo1zhPmD42rQKZ7j"
      database: "future_exchange"
      logging: false

    report:
      type: "mysql"
      host: "exchange-dev-mysql.clhjvle5bfjb.ap-northeast-2.rds.amazonaws.com"
      port: 3306
      username: "admin"
      password: "zo1zhPmD42rQKZ7j"
      database: "future_exchange"
      logging: false

    redis:
      host: "exchange-dev-redis.wt6mpg.0001.apn2.cache.amazonaws.com"
      port: 6379

    kafka:
      brokers: "10.0.2.51:9092"

    mail:
      enable: "false"
      service: "gmail"
      domain: "smtp.gmail.com"
      port: "465"
      account: ""
      password: ""
      from_address: ""
      from_name: "Future Exchange"

    insurance_account:
      user_id: 1

    insurance:
      account_id: "1"

    matching:
      funding_history_time: 28800000
      position_history_time: 86400000

    indices:
      interval: 5000

    health:
      namespace: "future-backend-dev"
      rpc_host: ""

    coin_info:
      coingeckoUrl: "https://api.coingecko.com/api/v3"

    dex:
      block_confirm: 12
      action_batch_size: 100
      block_time_in_ms: 3000
      chain_id: 1
      max_in_progress_action: 1000
      start_block: 0
      address: ""
      collateral_decimal: "6"
      default_scale: "8"
      matcher_private_key: ""
      rpc_host: ""
      running_chain: ""
      withdrawer_private_key: ""

    sol_dex:
      id: "1"
      action_batch_size: 100
      block_time_in_ms: 400
      max_in_progress_action: 1000
      usdc_id: "11111111111111111111111111111111"
      collateral_decimal: "6"
      default_scale: "8"
      matcher_private_key: "5MaiiCavjCmn9Hs1o3eznqDEhRwxo7pXiAYez7keQUviUkauRiTMD8DrESdrNjN8zd9mTmVhRvBJeg5vhyvgrAhG"
      program_id: "11111111111111111111111111111111"
      rpc_host: "https://api.devnet.solana.com"

    sharding:
      enabled: true
      shard1:
        symbols: "BTCUSDT,BTCBUSD,BTCUSDC"
        inputTopic: "matching-engine-shard-1-input"
        outputTopic: "matching-engine-shard-1-output"
      shard2:
        symbols: "ETHUSDT,ETHBUSD,ETHUSDC"
        inputTopic: "matching-engine-shard-2-input"
        outputTopic: "matching-engine-shard-2-output"
      shard3:
        symbols: ""
        inputTopic: "matching-engine-shard-3-input"
        outputTopic: "matching-engine-shard-3-output"
