app:
  name: "future-backend"
  prefix: "v1"
  port: 3000
  jwt_access_token_secret: "dev-jwt-secret-key-change-in-production"
  jwt_access_token_expiration_time: "86400"
  jwt_refresh_token_expiration_time: "604800"

jwt_key:
  public: ""
  private: ""

_master:
  type: "mysql"
  host: "host.docker.internal"
  port: 3306
  username: "root"
  password: "password"
  database: "future_exchange"
  logging: false

report:
  type: "mysql"
  host: "host.docker.internal"
  port: 3306
  username: "root"
  password: "password"
  database: "future_exchange"
  logging: false

redis:
  host: "host.docker.internal"
  port: 6379

kafka:
  brokers: "host.docker.internal:19092"

mail:
  enable: "false"
  service: "gmail"
  domain: "smtp.gmail.com"
  port: "465"
  account: ""
  password: ""
  from_address: ""
  from_name: "Future Exchange"

dex:
  block_confirm: 12

sharding:
  enabled: true
  shard1:
    symbols: "BTCUSDT,BTCBUSD,BTCUSDC"
    inputTopic: "matching-engine-shard-1-input"
    outputTopic: "matching-engine-shard-1-output"
  shard2:
    symbols: "ETHUSDT,ETHBUSD,ETHUSDC"
    inputTopic: "matching-engine-shard-2-input"
    outputTopic: "matching-engine-shard-2-output"
  shard3:
    symbols: ""
    inputTopic: "matching-engine-shard-3-input"
    outputTopic: "matching-engine-shard-3-output"
