apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - deployment.yaml
  - service.yaml
  - future-event-v2-consumers.yaml
  - ticker-worker.yaml
  - notify-worker.yaml
  - orderbook-worker.yaml
  - nginx-proxy.yaml

commonLabels:
  app.kubernetes.io/name: future-backend
  app.kubernetes.io/component: api

images:
  - name: exchange/future-backend
    newTag: "main"
    newName: 990781424619.dkr.ecr.ap-northeast-2.amazonaws.com/exchange/future-backend
