apiVersion: v1
kind: ConfigMap
metadata:
  name: exchange-socket-config
  namespace: exchange-stg
data:
  REDIS_HOST: "192.168.1.205"
  REDIS_PORT: "6382"
  REDIS_PREFIX: ""
  LARAVEL_ECHO_SERVER_REDIS_HOST: "192.168.1.205"
  LARAVEL_ECHO_SERVER_REDIS_PORT: "6382"
  LARAVEL_ECHO_SERVER_AUTH_HOST: https://api.exchange.sotatek.com