apiVersion: apps/v1
kind: Deployment
metadata:
  name: exchange-socket
  namespace: exchange-stg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exchange-socket
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: exchange-socket
    spec:
      containers:
      - name: exchange-socket
        imagePullPolicy: Always
        image: registry.gitlab.com/thanh89/exchange-misc:socket-v1.2
        ports:
        - containerPort: 6001
          name: http
          protocol: TCP
        resources:
          limits:
              cpu: 1
              memory: 2G
          requests:
            cpu: 1
            memory: 2G
        envFrom:
        - configMapRef:
            name: exchange-socket-config
      imagePullSecrets:
        - name: gitlab