apiVersion: v1
kind: Service
metadata:
  name: spot-backend-api
  labels:
    app: spot-backend
    component: api
spec:
  type: ClusterIP
  ports:
    - name: php-fpm
      port: 9000
      targetPort: 9000
      protocol: TCP
  selector:
    app: spot-backend
    component: api
