apiVersion: apps/v1
kind: Deployment
metadata:
  name: exchange-api
  namespace: exchange-stg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exchange-api
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: exchange-api
    spec:
      containers:
        - name: exchange-api
          imagePullPolicy: Always
          image: registry.gitlab.com/thanh89/sotatek-exchange-api:${VERSION}
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
          resources:
            limits:
              cpu: 1
              memory: 2G
            requests:
              cpu: 500m
              memory: 1G
          envFrom:
            - configMapRef:
                name: exchange-api-config
            - configMapRef:
                name: exchange-api-log-config
      imagePullSecrets:
        - name: gitlab
