apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
    name: exchange-api-ingress
    namespace: exchange-stg
    annotations:
      kubernetes.io/ingress.class: "nginx"
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
      nginx.ingress.kubernetes.io/rewrite-target: /
      nginx.ingress.kubernetes.io/secure-backends: "true"
      nginx.ingress.kubernetes.io/affinity: "cookie"
spec:
    rules:
    - host: api.exchange.sotatek.com
      http:
        paths:
        - backend:
            serviceName: exchange-api
            servicePort: 80
          path: /