apiVersion: v1
kind: Service
metadata:
  name: exchange-api
  namespace: exchange-stg
  labels:
    name: exchange-api
spec:
  selector:
    app: exchange-api
  type: LoadBalancer
  ports:
    - port: 80
      name: http
      targetPort: 80
