version: '3'
services:
  ticker-engine:
    #    platform: linux/x86_64
    build:
      context: .
      dockerfile: ./DockerfileTicker.dthbiy
    container_name: ticker-engine
    network_mode: "host"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"