version: '3'
services:
  ticker-engine:
#    platform: linux/x86_64
    build:
      context: .
      dockerfile: ./DockerfileTicker.prod
    container_name: ${TICKER_CONTAINER_NAME}
    network_mode: "host"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"