version: '3'
services:
  engine:
#    platform: linux/x86_64
    build:
      context: .
      dockerfile: ./DockerfileMe.dev
    container_name: ${ME_CONTAINER_NAME}
    network_mode: "host"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"