apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: matching-engine

labels:
  - pairs:
      app.kubernetes.io/managed-by: kustomize
      app.kubernetes.io/version: "1.0.0"
    includeSelectors: false

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - rbac.yaml
  - services.yaml
  - shard-1-statefulset.yaml
  - shard-2-statefulset.yaml
  - shard-3-statefulset.yaml
  - pdb.yaml
  - servicemonitor.yaml

images:
  - name: exchange/matching-engine-shard
    newTag: latest
